--- #YAML:1.0
name:               Xymon-Server-ExcelOutages
version:            0.03
abstract:           Produce an excel spreadsheet of outages
author:
    - David Peters (davidp@electronf.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Spreadsheet::WriteExcel:  2.37
    Test::Simple:         0.44
    Xymon::DB::Schema:    0.02
    Xymon::Server::History:  0.17
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
